wave_1_composition = {
    "Infantry" : 7,
    "Cloaker" : 3,
    "Shielder" : 5,
    "Sniper" : 1,
    "Saboteur" : 2,
}
wave_2_composition = {
    "Infantry" : 8,
    "Shielder" : 4,
    "Cloaker" : 2,
    "Saboteur" : 3,
    "Sniper" : 2,
}
wave_3_composition = {
    "Infantry" : 8,
    "Ranger" : 2.5,
    "Cloaker" : 2,
    "Shielder" : 3,
    "Saboteur" : 2,
    "Tranquilizer" : 1,

    "Boss" : 1,
}
wave_4_composition = {
    "Infantry" : 7,
    "Sniper" : 2,
    "Gunner" : 1,
    "APU" : 0.6,
    "Shielder" : 4,
    "Cloaker" : 2,
    "Ranger" : 4,
    "Medic" : 0.5,
    "Grenadier" : 0.3,
    "Saboteur" : 3,

    "Boss" : 1,
}
wave_5_composition = {
    "Infantry" : 6,
    "Medic" : 1,
    "Saboteur" : 3,
    "Shielder" : 4,
    "Cloaker" : 1,
    "Gunner" : 1,
    "APU" : 1,
    "Platform" : 0.5,
    "Sniper" : 1.5,
    "Jetpacker" : 1.2,

    "Boss" : 1,
}
wave_6_composition = {
    "Infantry" : 8,
    "Shielder" : 4,
    "Ranger" : 3,
    "APU" : 1,
    "Tank" : 0.5,
    "Saboteur" : 4,
    "Gunner" : 1,
    "Medic" : 0.5,
    "Engineer" : 0.5,
    "Grenadier" : 0.5,

    "Boss" : 2,
}
wave_7_composition = {
    "Infantry" : 7,
    "Shielder" : 3,
    "Engineer" : 0.5,
    "Grenadier" : 0.5,
    "APU" : 2,
    "Tank" : 2,
    "Platform" : 0.3,
    "Jetpacker" : 1.7,
    "Cloaker" : 2,
    "Saboteur" : 3,
    "Sniper" : 2,
    "Gunner" : 0.8,
    "Tranquilizer" : 1.5,
    "Medic" : 0.5,
    "Ranger" : 2,

    "Boss" : 2,
}
wave_8_composition = {
    "Infantry" : 8,
    "Shielder" : 4,
    "Engineer" : 0.8,
    "APU" : 1,
    "Tank" : 1,
    "Platform" : 0.3,
    "Jetpacker" : 2,
    "Cloaker" : 2,
    "Saboteur" : 3,
    "Sniper" : 1.5,
    "Gunner" : 0.8,
    "Tranquilizer" : 1.5,
    "Medic" : 0.6,
    "Ranger" : 2.5,

    "Boss" : 3,
}
wave_9_composition = {
    "Infantry" : 9,
    "Shielder" : 5,
    "Engineer" : 2,
    "Jetpacker" : 2,
    "Grenadier" : 0.5,
    "APU" : 2,
    "Tank" : 1.5,
    "Gunner" : 1.2,
    "Platform" : 0.5,
    "Medic" : 0.7,
    "Ranger" : 2.5,
    "Tranquilizer" : 2,
    "Saboteur" : 3,
    "Cloaker" : 3,
    "Sniper" : 2,

    "Boss" : 3,
}
wave_10_composition = {
    "Infantry" : 12,
    "Shielder" : 8,
    "Engineer" : 3,
    "Jetpacker" : 4,
    "Grenadier" : 2,
    "APU" : 3,
    "Tank" : 2,
    "Gunner" : 4,
    "Platform" : 2,
    "Medic" : 1.5,
    "Ranger" : 5,
    "Tranquilizer" : 5,
    "Saboteur" : 8,
    "Cloaker" : 5,
    "Sniper" : 4,

    "Boss" : 5,
}
wave_11_composition = {
    "Infantry" : 40,
    "Shielder" : 20,
    "Engineer" : 4,
    "Jetpacker" : 5,
    "Grenadier" : 3,
    "APU" : 4,
    "Tank" : 4,
    "Gunner" : 7,
    "Platform" : 3,
    "Medic" : 4,
    "Ranger" : 10,
    "Tranquilizer" : 9,
    "Saboteur" : 12,
    "Cloaker" : 18,
    "Sniper" : 12,
    "Boss" : 9,
    "Ares" : 1,
}