composition = {
    "Infantry" : 12,
    "Shielder" : 8,
    "Engineer" : 3,
    "Jetpacker" : 4,
    "Grenadier" : 2,
    "APU" : 3,
    "Tank" : 2,
    "Gunner" : 4,
    "Platform" : 2,
    "Medic" : 1.5,
    "Ranger" : 5,
    "Tranquilizer" : 5,
    "Saboteur" : 8,
    "Cloaker" : 5,
    "Sniper" : 4,
    "Boss" : 5,
}