wave_9_composition = {
    "Infantry" : 9,
    "Shielder" : 5,
    "Engineer" : 2,
    "Jetpacker" : 2,
    "Grenadier" : 0.5,
    "APU" : 2,
    "Tank" : 1.5,
    "Gunner" : 1.2,
    "Platform" : 0.5,
    "Medic" : 0.7,
    "Ranger" : 2.5,
    "Tranquilizer" : 2,
    "Saboteur" : 3,
    "Cloaker" : 3,
    "Sniper" : 2,
    "Boss" : 3,
}