
wave_11_composition = {
    "Infantry" : 40,
    "Shielder" : 20,
    "Engineer" : 4,
    "Jetpacker" : 5,
    "Grenadier" : 3,
    "APU" : 4,
    "Tank" : 4,
    "Gunner" : 7,
    "Platform" : 3,
    "Medic" : 4,
    "Ranger" : 10,
    "Tranquilizer" : 9,
    "Saboteur" : 12,
    "Cloaker" : 18,
    "Sniper" : 12,
    "Boss" : 9,
    "Ares" : 1,
}