composition = {
    "Infantry" : 8,
    "Shielder" : 4,
    "Engineer" : 0.8,
    "APU" : 1,
    "Tank" : 1,
    "Platform" : 0.3,
    "Jetpacker" : 2,
    "Cloaker" : 2,
    "Saboteur" : 3,
    "Sniper" : 1.5,
    "Gunner" : 0.8,
    "Tranquilizer" : 1.5,
    "Medic" : 0.6,
    "Ranger" : 2.5,
    "Boss" : 3,
}