composition = {
    "Infantry" : 7,
    "Shielder" : 3,
    "Engineer" : 0.5,
    "Grenadier" : 0.5,
    "APU" : 2,
    "Tank" : 2,
    "Platform" : 0.3,
    "Jetpacker" : 1.7,
    "Cloaker" : 2,
    "Saboteur" : 3,
    "Sniper" : 2,
    "Gunner" : 0.8,
    "Tranquilizer" : 1.5,
    "Medic" : 0.5,
    "Ranger" : 2,
    "Boss" : 2,
}